### ISSUE TITLE
Swift support?

### ISSUE THREAD

**Issue by msmollin** [MacDownApp/handlebars-objc#3]
Looking at using Handlebars or something similar in an iOS app being written in Swift. What pitfalls do you think I should watch out for here or that I might be able to help fix?

**Comment by FranklinYu** [comment]
This forks is only for MacDown itself. Swift support is beyond the scope of this fork until MacDown is converted to Swift. Features like this should probably go upstream.

**Comment by msmollin** [comment]
Ugh. You mean the upstream that's been abandoned for years? :( Guess I'll just do it myself then.

**Comment by FranklinYu** [comment]
Well, if you create PR we may be able to review and merge it, but we don’t have the time to develop a new feature. Sorry.
